Addition of beccus to ETM
quintel/etmodel pull request #4220
Opened 2024-03-19 13:19 UTC by kaskranenburgQ

With this update, the option to model BECC(U)S plants with the ETM becomes possible.

For the ETModel repository this means the following changes have been implemented:

- Addition of sliders which set the capacity of biomass plants that only produce power.
- Addition of sliders for dispatchable biomass plants.
- Addition of sliders for CCS for all biomass plants.
- Addition of sliders for Full load hours for must-run biomass plants.
- Addition of these new biomass plants to relevant graphs.
- Addition of slider voor captured biogenic co2 price.
- Creation of new graph called : " Net effect of demand and supply of CO2 on emissions".

2024-03-21 09:45 UTC, mabijkerk requested changes

2024-03-21 09:45 UTC, mabijkerk commented on config/locales/interface/input_elements/en_costs.yml
> +        CO<sub>2</sub> removal price is set lower than the CO<sub>2</sub> price, it would be
This description and should be updated to match the **captured biogenic CO2 price**. This also goes for the nl locales.

2024-03-21 09:55 UTC, mabijkerk commented
I think the frontend of the Captured and Imported CO2 slide in CCUS section is quite cluttered. I would prefer a more clear section with multiple slides. These would be the proposed slides:

- Overview (optional)
- Capture of CO2 in energy sector
  - DAC
  - Power plants
  - Hydrogen plants
- Capture of CO2 in industry sector
- Import of CO2

Additionally, the full load hours for must-run CCS biomass can go to the Costs & efficiencies section.

2024-03-21 10:20 UTC, mabijkerk commented
It seems to me that a new series needs to be added to both costs charts (detailed and overview). This series should specify the costs of captured biogenic CO2.

![Screenshot 2024-03-21 at 11 19 21](https://github.com/quintel/etmodel/assets/67338510/da11647c-3466-4ab8-ae5c-f5489bbc27dc)

2024-03-22 09:41 UTC, mabijkerk approved these changes
Nice work y'all!

2024-03-22 12:57 UTC, mabijkerk requested changes
For a blank nl2019 scenario, there is demand and supply of CO2, which is clearly shown in the table view of the new waterfall chart:

<img width="628" alt="Screenshot 2024-03-22 at 13 56 03" src="https://github.com/quintel/etmodel/assets/67338510/5f4c54a5-be8d-4199-aa8c-65007077b6d1">

However, when I look at the chart view, this supply and demand does not appear:
<img width="620" alt="Screenshot 2024-03-22 at 13 56 53" src="https://github.com/quintel/etmodel/assets/67338510/aea4aeff-f9f8-456e-8376-6a205225abfb">

2024-03-25 10:01 UTC, noracato commented
> Adding any new flows does work, but still does not make the existing flows visible.

This is entirely expected behaviour.

The waterfall chart by default shows the change between present and future. In your table view you see that present and future are the same, so there is a difference of 0 shown in the chart. When you then change the future capture to export, you can see the changes reflected in the chart.

What was your idea of what the chart has to show? There are also options to show only data of the future, or of the present instead of showing the difference.

2024-03-25 15:29 UTC, mabijkerk approved these changes

2024-03-25 15:30 UTC, merged